name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 17 * * 5'

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install protobuf-compiler libprotobuf-dev libboost-all-dev libgtest-dev libgmock-dev valgrind

      - name: Configure
        run: |
          cmake -B build

      - name: Build
        run: |
          cmake --build build

      - name: Unit Test
        run: |
          cmake --build build --target test

      - name: Memcheck
        working-directory: build
        run: |
          valgrind --error-exitcode=1 ./alltests